Update diagnostic server to get IPs from metaserver instead (#628)
Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

diff --git a/aws/dockerfiles/files/bin/docker-diagnose b/aws/dockerfiles/files/bin/docker-diagnose
--- a/aws/dockerfiles/files/bin/docker-diagnose
+++ b/aws/dockerfiles/files/bin/docker-diagnose
@@ -19,35 +19,20 @@ platform()
 	fi
 }
 
-node_hostnames()
-{
-	docker node inspect $(docker node ls -q) | jq -r '.[] | .Description.Hostname'
-}
-
-azure_resolver()
-{
-	# Sample /etc/resolv.conf on Azure:
-	#
-	# # Generated by dhcpcd from eth0.dhcp
-	# # /etc/resolv.conf.head can replace this line
-	# domain zopqyteo2tpuxc1cyzroivpijh.gx.internal.cloudapp.net
-	# nameserver 168.63.129.16
-	# # /etc/resolv.conf.tail can replace this line
-	#
-	cat /etc/resolv.conf | grep domain | awk '{ print $2; }'
-}
-
 if [ "$(platform)" = "aws" ]
 then
-	NODES=$(node_hostnames)
+	# Get instance private IP from AWS metadata service if on AWS.
+	METASERVER_ADDR=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4/)
 else
-	# We need to append to the hostnames with the DNS resolver address, or
-	# else they won't resolve properly.
-	#
-	# We could potentially modify swarm to accept a "hostname" (more
-	# properly nodename) type flag on join, but no such option seems
-	# available today.
-	NODES=$(node_hostnames | sed -e "s/$/.$(azure_resolver)/")
+	# Azure shell is run with --net host so use localhost.
+	METASERVER_ADDR=localhost
+fi
+
+NODES=$(curl -s "${METASERVER_ADDR}:9024/instances/all/")
+if [ $? -ne 0 ]; then
+	>&2 echo "Sorry, there was an error getting IPs for the cluster."
+	>&2 echo "Are you invoking $0 from a manager node?"
+	exit 1
 fi
 
 # Session is set to a pseudo-random string combined with the current timestamp.
